# Generated by Django 4.0.6 on 2022-07-07 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')])),
                ('last_name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid last name. Minimum 2 and maximum 64 alphabets allowed.', regex='^[a-zA-Z]{2,64}$')])),
                ('email', models.EmailField(max_length=64)),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. Digit length should be 10.', regex='^[0-9]{10}$')])),
                ('role', models.CharField(choices=[('admin', 'Admin - Can delete members'), ('regular', "Regular - Can't delete members")], default='regular', max_length=32)),
                ('canDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
