# Generated by Django 4.0.6 on 2022-07-07 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. Digit length should be 10.', regex='^[0-9]{10}$')]),
        ),
    ]
